import "quill/dist/quill.snow.css";
import "./styles/globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import AuthProvider from "./providers/auth-provider";
import { MSWProvider } from "./providers/msw-provider";
import QueryProvider from "./providers/queryProvider";

const pretendard = localFont({
  src: "../public/fonts/pretendard/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (typeof window === "undefined" && process.env.NODE_ENV === "development") {
  const { server } = await import("@/mocks/server");
  server.listen();
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} antialiased`}>
        <MSWProvider>
          <AuthProvider>
            <QueryProvider>
              <SidebarProvider>{children}</SidebarProvider>
            </QueryProvider>
          </AuthProvider>
        </MSWProvider>
        <Toaster className="w-full h-20 flex flex-col justify-center relative" />
      </body>
    </html>
  );
}
